site_name: ä¹å°˜é“äººçš„ä¸»é¡µ
site_url: https://blog.transcliff.top
docs_dir: src
site_dir: site
theme:
  name: material
  palette:
    scheme: preference
    primary: blue grey
  language: "zh"
  icon:
    logo: material/candelabra
  favicon: favicon.svg
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - header.autohide
extra:
  social:
    - icon: fontawesome/regular/envelope
      link: mailto:admin@mail.transcliff.top
  generator: false
markdown_extensions:
  - toc:
      permalink: ğŸ•¯
plugins:
  - git-revision-date-localized:
      type: timeago
      fallback_to_build_date: true
  - search:
      prebuild_index: true

copyright: <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.

nav:
  - ä¸»é¡µ: index.md
  - å…³äº: about.md
